#!/bin/bash

# $1 = settingsFileName
# $2 = plutoDestination

# sshpass -p analog scp -O /home/pi/Q100/settings.txt plutosdr:/www/ > /dev/null 2>&1
# (the -O flag tell sftp to use the legacy method)
# possible error: Host key verification failed.  Need to login to Pluto at least once after installing

/usr/bin/sshpass -p analog /usr/bin/scp -O $1 $2 > /dev/null 2>&1
