#!/bin/bash
# $1 = settingsFileName
# $2 = plutoDestination

# /usr/bin/sshpass -panalog /usr/bin/scp /home/pi/Q100/settings.txt root@pluto.local:/www/ > /dev/null 2>&1

# possible error is: Host key verification failed.  Need to login to Pluto at least once after installing

/usr/bin/sshpass -panalog /usr/bin/scp $1 $2 > /dev/null 2>&1
